### ISSUE TITLE
Complete IBM Developer Technology checklist

### ISSUE THREAD

**Issue by krook** [IBM/openwhisk-serverless-apis#7]
**Guidelines**
- [x] Source Code + Documentation on Github   (github.com/ibm)
- [x] Apache 2.0 License
- [x] Detailed documentation in README.md
- [ ] Insured by peer reviews, one each from technology and advocacy team as applicable
- [x] Code updates/fixes/PRs
- [x] CONTRIBUTING. md and MAINTAINERS. md file to be added
- [x] Github repo owner has commit/merge privileges
- [x] Scenario issues are filed and triaged through Github. 
- [ ] Issues have to be triaged and responded to (not solved) within 72 (working) hours.
- [x] A successful Travis CI build should be a requirement for successful merge

**README elements**
- [x] Overview: 
- [x] Detailed installation/deployment steps. E.g.: 
Setting up the environment (provisioning services)
Setting up Component A
Setting up Component B
Setting up Component C
- [x] Runtime instructions (end user documentation)
- [x] Accessing/running the scenario
- [x] End to end testing of the scenario
- [x] Troubleshooting
